# Generated by Django 5.2.13 on 2026-05-04 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('is_on_grid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=3)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('is_on_grid', models.BooleanField(default=True)),
                ('is_reserve', models.BooleanField(default=False)),
                ('constructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='f1data.constructor')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('is_sprint_weekend', models.BooleanField(default=False)),
                ('is_complete', models.BooleanField(default=False)),
                ('fp1_at', models.DateTimeField(blank=True, null=True)),
                ('fp2_at', models.DateTimeField(blank=True, null=True)),
                ('fp3_at', models.DateTimeField(blank=True, null=True)),
                ('sprint_quali_at', models.DateTimeField(blank=True, null=True)),
                ('sprint_at', models.DateTimeField(blank=True, null=True)),
                ('quali_at', models.DateTimeField(blank=True, null=True)),
                ('race_at', models.DateTimeField(blank=True, null=True)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='f1data.circuit')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='f1data.season')),
            ],
            options={
                'ordering': ['round'],
                'unique_together': {('season', 'round')},
            },
        ),
        migrations.CreateModel(
            name='DriverChampionshipStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('points', models.FloatField(default=0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='championship_standings', to='f1data.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_standings', to='f1data.race')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('race', 'driver')},
            },
        ),
        migrations.CreateModel(
            name='ConstructorChampionshipStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('points', models.FloatField(default=0)),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='championship_standings', to='f1data.constructor')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constructor_standings', to='f1data.race')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('race', 'constructor')},
            },
        ),
        migrations.CreateModel(
            name='RaceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('finish_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_substitute', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_entries', to='f1data.constructor')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_entries', to='f1data.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='f1data.race')),
                ('substituted_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substituted_entries', to='f1data.driver')),
            ],
            options={
                'unique_together': {('race', 'driver')},
            },
        ),
    ]
