# Generated by Django 5.2.13 on 2026-05-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceentry',
            name='is_fastest_lap',
            field=models.BooleanField(default=False),
        ),
    ]
