# Generated by Django 5.2.13 on 2026-05-04 18:59

import paddocks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paddock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('join_code', models.CharField(default=paddocks.models.generate_join_code, max_length=6, unique=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_world_paddock', models.BooleanField(default=False)),
                ('max_players', models.PositiveSmallIntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaddockDeadlineReopening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline_type', models.CharField(choices=[('driver_standing', 'Driver Standing'), ('constructor_standing', 'Constructor Standing')], max_length=25)),
                ('reopened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaddockMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaddockPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PaddockRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('racely_deadline_session', models.CharField(choices=[('Q1', 'Q1 / Qualifying'), ('SPRINT', 'Sprint Race'), ('FP1', 'FP1')], default='Q1', max_length=10)),
                ('racely_start_round', models.PositiveSmallIntegerField(default=1)),
                ('racely_scoring_positions', models.PositiveSmallIntegerField(default=10)),
                ('driver_standing_deadline_session', models.CharField(choices=[('Q1', 'Q1 / Qualifying'), ('SPRINT', 'Sprint Race'), ('FP1', 'FP1')], default='Q1', max_length=10)),
                ('driver_standing_start_round', models.PositiveSmallIntegerField(default=1)),
                ('constructor_standing_deadline_session', models.CharField(choices=[('Q1', 'Q1 / Qualifying'), ('SPRINT', 'Sprint Race'), ('FP1', 'FP1')], default='Q1', max_length=10)),
                ('constructor_standing_start_round', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_type', models.CharField(choices=[('before', 'Before'), ('after', 'After')], max_length=10)),
                ('prediction_data', models.JSONField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
