# Generated by Django 5.2.13 on 2026-05-04 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('f1data', '0001_initial'),
        ('paddocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paddock',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_paddocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paddock',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paddocks', to='f1data.season'),
        ),
        migrations.AddField(
            model_name='paddockdeadlinereopening',
            name='paddock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_reopenings', to='paddocks.paddock'),
        ),
        migrations.AddField(
            model_name='paddockdeadlinereopening',
            name='reopened_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_reopenings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paddockmembership',
            name='paddock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='paddocks.paddock'),
        ),
        migrations.AddField(
            model_name='paddockmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paddock_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paddockpool',
            name='constructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pool_entries', to='f1data.constructor'),
        ),
        migrations.AddField(
            model_name='paddockpool',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pool_entries', to='f1data.driver'),
        ),
        migrations.AddField(
            model_name='paddockpool',
            name='paddock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_entries', to='paddocks.paddock'),
        ),
        migrations.AddField(
            model_name='paddockrules',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paddock_rules', to='f1data.season'),
        ),
        migrations.AddField(
            model_name='paddock',
            name='rules',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paddock', to='paddocks.paddockrules'),
        ),
        migrations.AddField(
            model_name='predictionsnapshot',
            name='reopening',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='paddocks.paddockdeadlinereopening'),
        ),
        migrations.AddField(
            model_name='predictionsnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='paddockmembership',
            unique_together={('paddock', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='paddockpool',
            unique_together={('paddock', 'constructor'), ('paddock', 'driver')},
        ),
    ]
