# Generated by Django 5.2.13 on 2026-05-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paddocks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paddock',
            name='max_players',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
