# Generated by Django 5.2.13 on 2026-05-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RacelyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_points', models.FloatField(default=0)),
                ('pole_points', models.FloatField(default=0)),
                ('fastest_lap_points', models.FloatField(default=0)),
                ('quiz_points', models.FloatField(default=0)),
                ('quiz_pending', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_standing_points', models.FloatField(default=0)),
                ('constructor_standing_points', models.FloatField(default=0)),
            ],
        ),
    ]
