# Generated by Django 5.2.13 on 2026-05-04 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('f1data', '0001_initial'),
        ('leaderboards', '0001_initial'),
        ('paddocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='racelyscore',
            name='paddock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racely_scores', to='paddocks.paddock'),
        ),
        migrations.AddField(
            model_name='racelyscore',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racely_scores', to='f1data.race'),
        ),
    ]
