# Generated by Django 5.2.13 on 2026-05-04 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('f1data', '0001_initial'),
        ('leaderboards', '0002_initial'),
        ('paddocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='racelyscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racely_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seasonscore',
            name='paddock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_scores', to='paddocks.paddock'),
        ),
        migrations.AddField(
            model_name='seasonscore',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_scores', to='f1data.race'),
        ),
        migrations.AddField(
            model_name='seasonscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='racelyscore',
            unique_together={('user', 'paddock', 'race')},
        ),
        migrations.AlterUniqueTogether(
            name='seasonscore',
            unique_together={('user', 'paddock', 'race')},
        ),
    ]
